### ISSUE TITLE
Only option in opencore is "Reset NVRAM".

### ISSUE THREAD

**Issue by ghost** [alkalim/ryzen-catalina#6]
I have Ryzen 5 2600 and AsRock B450 Pro4 Motherboard I have 2 Drives: One has Windows (SSD) and one will have Mac (HDD). But when I boot my USB in UEFI mode with your repo (I also have configured config.plist) the only options I have as an operating system is 1. Reset NVRAM and when I choose it, it just restarts me and boots me into Windows. What have I done wrong? Does it work with 2 Drives?

Edit: I just noticed after I boot from my usb before booting into opencore a text pops up saying OCS: Failed to parse data field as value with type data and <**my mac address**> contents, context < ROM > !

**Comment by giqrgakhs** [comment]
Hi, I eventually got it to work but internet doesn't work i have a tp-link adapter

**Comment by alkalim** [comment]
Hello, it should work with two drives. Moreover, two drives is a recommended setup. 

Did you go through step #2 and edit your PlatformInfo as described here: https://github.com/alkalim/ryzen-catalina#step-2---update-configplist ?

**Comment by ghost** [comment]
Yes I Did, the only things I edited were SystemSerialNumber, SystemUUID, MLB, ROM and since we have the same CPU and Mobo I downloaded your repo

**Comment by alkalim** [comment]
I reproduced this error by changing ROM to a random string. Then I get exactly the same error message on boot. The reason is ROM has the type _data_ which requires special encoding. Did you edit this field with ProperTree?

On boot, OpenCore looks for bootable volumes. If you only see NVRAM reset this means OC doesn't find your OSes. It either didn't install correctly (did you run gibMacOS.bat and MakeInstall.bat?) or doesn't see your drives at all. In the latter case you might want to double-check your BIOS settings in accordance with the OC guide.

**Comment by ghost** [comment]
Hi I edited config.plist < ROM > correctly? with ProperTree and I got it to work, the problem is that the installer is in russian and I have not internet whatsoever

**Comment by alkalim** [comment]
That's a very well known problem, please see this: https://dortania.github.io/OpenCore-Install-Guide/troubleshooting/extended/userspace-issues.html#macos-installer-in-russian

**Comment by ghost** [comment]
What about Ethernet?

**Comment by giqrgakhs** [comment]
?

**Comment by alkalim** [comment]
> What about Ethernet?

No idea what you mean. If you have specific error you can post it here but you will have higher chances to get help in Amd-osx forum.
